### ISSUE TITLE
Issue 120: How to calculate the path in this triangle?

### ISSUE THREAD

**Issue by Rangooo123** [LahElr/DailyPractice#1]
**My idea**
From top point $(1,1)$ with a value $a_{1,1}$, to the most down right point $(n,n)$ with a value $a_{n,n}$ ?
If so, the path value $P$ should at least be  $a_{1,1} + a_{n,n}$ ?

**Comment by LahElr** [comment]
For the whole triangle, the most down right point does not necessarily be on the path; for one single path, it does not hole since the numbers can be negative.

**Comment by Rangooo123** [comment]
Thank you my master
